FROM pagespeed/nginx-pagespeed

ARG PORT

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/dev.conf /etc/nginx/include/dev.conf
RUN sed -i "s/PORT/${PORT}/g" /etc/nginx/include/dev.conf

COPY nginx/ssl_crt.pem /etc/nginx/ssl_crt.pem
COPY nginx/ssl_key.pem /etc/nginx/ssl_key.pem
# COPY ./public /usr/share/nginx/html/

WORKDIR /usr/share/nginx/html/
EXPOSE 80 443